name: Build and Publish Android Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Android Package
      run: |
        # Ensure you have python-for-android installed
        pip install python-for-android
        # Build the APK with specified requirements
        p4a apk --private . \
          --package=my_firebase_admin \
          --name="MyFirebaseAdmin" \
          --version=0.1 \
          --bootstrap=python3crystax \
          --requirements=firebase-admin \
          --requirements=cachecontrol \
          --requirements=msgpack \
          --requirements=google-api-core \
          --requirements=google-auth \
          --requirements=pyasn1-modules \
          --requirements=rsa \
          --requirements=six \
          --requirements=protobuf \
          --requirements=google-cloud-firestore \
          --requirements=google-cloud-core

    - name: List APK files
      run: |
        ls -la bin/*.apk
