name: Build and Publish Android Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Android Package
      run: |
        # Ensure you have python-for-android installed
        pip install python-for-android
        # Build the APK with specified requirements
        p4a apk --private . \
          --package=my_firebase_admin \
          --name="MyFirebaseAdmin" \
          --version=0.1 \
          --bootstrap=python3crystax \
          --requirements=firebase-admin,cachecontrol>=0.12.6,<0.13.0,msgpack>=0.5.2,google-api-core>=1.22.1,<3.0.0,google-auth>=1.25.0,<3.0dev,pyasn1-modules>=0.2.1,rsa>=3.1.4,<5,six>=1.9.0,protobuf>=3.20.0,<5.0.0dev,google-cloud-firestore>=2.0.0,<3.0.0,google-cloud-core

    - name: List APK files
      run: |
        ls -la bin/*.apk
        
