name: Build and Publish Android Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip
        pip install git+https://github.com/flet-dev/python-for-android.git@3.11.6
        pip install --upgrade cython

    - name: Upload requirements.txt
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found!"
          exit 1
        fi
        cat requirements.txt

    - name: Set up Android SDK
      run: |
        # Create the Android SDK directory in the runner's home
        mkdir -p $HOME/Android/Sdk/cmdline-tools

        # Download and install command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d $HOME/Android/Sdk/cmdline-tools/
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

        # Set environment variables for Android SDK
        echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools" >> $GITHUB_ENV

        # Install required SDK components for API level 34
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

        # Verify the SDK installation
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --list

    - name: Install Android NDK
      run: |
        NDK_VERSION="25.2.9519653"
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;$NDK_VERSION" --channel=3

        # Add NDK toolchains to the PATH
        echo "PATH=$PATH:$ANDROID_SDK_ROOT/ndk/$NDK_VERSION/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

    - name: Build Android Package
      run: |
        # Use requirements.txt file for building the Android package
        p4a create --requirements=$(paste -s -d, requirements.txt) --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_SDK_ROOT/ndk/$NDK_VERSION --dist-name mydist

    - name: List APK files
      run: |
        ls -la $HOME/Android/Sdk/bin/*.apk
